- name: Checkout code
  uses: actions/checkout@v3

# 1️⃣ Setup pnpm FIRST
- name: Setup pnpm
  uses: pnpm/action-setup@v2
  with:
    version: 9

# 2️⃣ THEN setup Node with caching
- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 22
    cache: 'pnpm'

# Continue with install/build/deploy
- name: Install dependencies
  run: pnpm install

- name: Build project
  run: pnpm build

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./dist
